# Custom workflow for adding appropriate resource links for new article html pages

name: resource-check

on: [push, workflow_dispatch]

jobs:
  add-article-css:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: check for links
        working-directory: .
        run: python3 ./.github/workflows/add_article_decor.py
          
      - name: commit changes
        uses: EndBug/add-and-commit@v6
        with:
          message: 'Automatically added resource links (GitHub Action)'
          add: pages
