# Custom workflow for adding appropriate css links for new article html pages

name: css-check

on: [push, pull_request, workflow_dispatch]

jobs:
  add-article-css:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      # check html files in pages dir for article.css reference. if css ref missing, it will be added
      - name: check for css
        working-directory: .
        run: |
          PAGESPATH=./pages/*/
          for dir in $PAGESPATH
          do
            for f in $dir*.html
            do
              echo $dir $f
              lookfor='article.css'
              match="<head>"
              insert="<link rel='stylesheet' href='../../css/main.css'/>\n<link rel='stylesheet' href='../../css/article.css'/>"
              if [[ -z "$(grep $lookfor $f)" ]]
              then
                sed -i "/$match/a $insert" $f
              fi
            done
          done
          
      - name: commit changes
        uses: EndBug/add-and-commit@v6
        with:
          message: 'Automatically added CSS to article (gh action)'
          add: pages